image: maven:latest
variables:
  SONAR_TOKEN: $SONAR_TOKEN_BACKEND
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend:
  stage: sonar
  script:
    - cd "${CI_PROJECT_DIR}/backend"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bootcamp-35-dossier-backend -Dsonar.login=$SONAR_TOKEN_BACKEND -Dsonar.organization=zemoso-int
      -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - dev
    - main
